name: Build Electron Application
on:
  push:
    branches:
      - develop
jobs:
  build_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: develop
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - run: git config --global user.name "Github Actions"
      - run: git config --global user.email "github-actions@github.com"
      - run: npm version $(node -p "require('./package.json').version")-beta.${{ github.sha}}
      - name: build
        run: npm run build:mac-prerelease
